#Vaadin Copilot Integration Runtime Properties
#Tue Dec 16 09:57:55 EET 2025
endpoint=http\://127.0.0.1\:57712/vaadin/copilot-f22d7004-28c5-4d21-9bf2-c625f6107369
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
