#Vaadin Copilot Integration Runtime Properties
#Tue Mar 17 19:27:52 EET 2026
endpoint=http\://127.0.0.1\:49623/vaadin/copilot-c5a5a090-6240-4fa5-afa1-d0ccb6b44084
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
