#Vaadin Copilot Integration Runtime Properties
#Fri Apr 03 15:38:32 EEST 2026
endpoint=http\://127.0.0.1\:49365/vaadin/copilot-85d87d88-5045-45dd-b62e-82e9b63b4937
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
